### ISSUE TITLE
2 errori riscontrati con dei comandi per il prompt.

### ISSUE THREAD

**Issue by ChristianMascolo** [xrmx/un-corso-django#48]
Al capitolo 5.5 ho provato a utilizzare il comando touch su win10 ma esso non funziona, e sulla lista dei comandi non lo trovo quindi ho optato per creare il file a mano. Un altro errore che capita è provando a scrivere sul prompt corsi/tests ,questo perchè su win10 va usato \ invece di /. Sono piccolezze lo so ma lo dico per correttezza,

**Comment by callmesangio** [comment]
Ciao,

penso che il corso dia per scontato l'utilizzo di Linux o MacOS come sistema operativo, almeno negli esempi.

> Tutti gli esempi vengono fatti per un sistema operativo UNIX-like ed è previsto l'uso della shell.

https://un-corso-django.netlify.app/ch00-00-introduzione.html

**Comment by ChristianMascolo** [comment]
Ah,scusatemi allora. Su windows infatti molte cose sono diverse e alcuni passaggi sono anche un extra

**Comment by xrmx** [comment]
Dice bene @sanjioh, chiudo la issue. Grazie.
